// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csogvdvbkbxphfhlqhqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzb2d2ZHZia2J4cGhmaGxxaHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTU4MTMsImV4cCI6MjA2OTI3MTgxM30.9l0s9FHpPE6v-P3NkQRcQ4-I3Fhf7nAIH4d1bsfYsOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});